config/routes.rb
Rails.application.routes.draw do
  get 'users/create'
  resources :uses
  resources :items
  root 'home#index'
  devise_for :users

  scope module: 'api' do
    namespace :v1 do
      resources :items
      resources :uses
      resources :users
      get "/getUseDate", to: "items#getUseDate"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/api/v1/api_recond.rb
module Api::V1
  class ApiRecond < ActiveRecord::Base
    self.abstract_class = true
    scope :getAll_desc,->{order(id: :desc)}
    scope :findbyId,->id{find(id)}
  end
end

app/models/api/v1/item.rb
module Api::V1
  class Item < ApiRecond
    mount_uploader :image, ImageUploader
    has_many :uses
    scope :getUseAll, ->{joins(:uses).select("uses.*,items.name, items.old_cost, items.new_cost, items.unit, items.image")}
    scope :getDate, ->(id,date){joins(:uses).select("uses.*,items.name, items.old_cost, items.new_cost, items.unit,items.image").where("uses.date = ? AND uses.user_id= ?",date,id)}
  end
end

app/models/api/v1/use.rb
module Api::V1
  class Use < ApiRecond
    belongs_to :item
  end
end

app/models/api/v1/users.rb
module Api::V1
  class User < ApiRecond
   scope :getAll,{order(id: :desc)}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :image, ImageUploader
  
end

app/models/use.rb
class Use < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/apis_controller.rb
module Api::V1
  class ApisController < ApplicationController
    skip_before_action :authenticate_user!
    skip_before_action :verify_authenticity_token
  end
end

app/controllers/api/v1/items_controller.rb
module Api::V1
  class ItemsController < ApisController
    def index
      uses = Item.getUseAll
      render json: {data: uses}
    end

    def getUseDate
      date = params[:date]
      id = params[:id]
      render json: {data: Item.getDate(id,date)}
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api::V1
  require "bcrypt"
  class UsersController < ApisController
    def create
      email = params[:email]
      password = params[:password]
      user = User.find_by_email(email)
      if !user.nil?
        user_pass = BCrypt::Password.new(user.encrypted_password)
        if user_pass == password
          render json: {status: 200, data: user}
        else
          render json: {status: 402}
        end
      else 
        render json: {status: 404}
      end
    end
  end
end

app/controllers/api/v1/uses_controller.rb
module Api::V1
    class UsesController < ApisController
      
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.remove_image!
    @item.save
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :old_cost, :new_cost, :unit, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
  end
end

app/controllers/uses_controller.rb
class UsesController < ApplicationController
  before_action :set_use, only: %i[ show edit update destroy ]

  # GET /uses or /uses.json
  def index
    @uses = Use.all
  end

  # GET /uses/1 or /uses/1.json
  def show
  end

  # GET /uses/new
  def new
    @use = Use.new
  end

  # GET /uses/1/edit
  def edit
  end

  # POST /uses or /uses.json
  def create
    @use = Use.new(use_params)

    respond_to do |format|
      if @use.save
        format.html { redirect_to @use, notice: "Use was successfully created." }
        format.json { render :show, status: :created, location: @use }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @use.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uses/1 or /uses/1.json
  def update
    respond_to do |format|
      if @use.update(use_params)
        format.html { redirect_to @use, notice: "Use was successfully updated." }
        format.json { render :show, status: :ok, location: @use }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @use.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uses/1 or /uses/1.json
  def destroy
    @use.destroy
    respond_to do |format|
      format.html { redirect_to uses_url, notice: "Use was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_use
      @use = Use.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def use_params
      params.require(:use).permit(:amount, :date, :note, :user_id, :item_id, :date)
    end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/uses_helper.rb
module UsesHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :old_cost %>
    <%= form.text_field :old_cost %>
  </div>

  <div class="field">
    <%= form.label :new_cost %>
    <%= form.text_field :new_cost %>
  </div>

  <div class="field">
    <%= form.label :unit %>
    <%= form.text_field :unit %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Old cost</th>
      <th>New cost</th>
      <th>Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.old_cost %></td>
        <td><%= item.new_cost %></td>
        <td><%= item.unit %></td>
        <td><%=item.image%></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Old cost:</strong>
  <%= @item.old_cost %>
</p>

<p>
  <strong>New cost:</strong>
  <%= @item.new_cost %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @item.unit %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/uses/_form.html.erb
<%= form_with(model: use, local: true) do |form| %>
  <% if use.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(use.errors.count, "error") %> prohibited this use from being saved:</h2>

      <ul>
      <% use.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note %>
  </div>
  <div class="field">
    <%= form.label :item_id %>
    <%= form.text_field :item_id %>
  </div>
  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/uses/edit.html.erb
<h1>Editing Use</h1>

<%= render 'form', use: @use %>

<%= link_to 'Show', @use %> |
<%= link_to 'Back', uses_path %>

app/views/uses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Uses</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Date</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uses.each do |use| %>
      <tr>
        <td><%= use.amount %></td>
        <td><%= use.date %></td>
        <td><%= use.note %></td>
        <td><%= link_to 'Show', use %></td>
        <td><%= link_to 'Edit', edit_use_path(use) %></td>
        <td><%= link_to 'Destroy', use, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Use', new_use_path %>

app/views/uses/new.html.erb
<h1>New Use</h1>

<%= render 'form', use: @use %>

<%= link_to 'Back', uses_path %>

app/views/uses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @use.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @use.date %>
</p>

<p>
  <strong>Note:</strong>
  <%= @use.note %>
</p>

<%= link_to 'Edit', edit_use_path(@use) %> |
<%= link_to 'Back', uses_path %>